# Generated by Django 5.2 on 2025-05-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('boards', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='customers', to='boards.board'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='products.productitem'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_items',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to='products.productitem'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to='products.productitem'),
        ),
    ]
