# Generated by Django 5.2 on 2025-05-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_remove_user_username'),
        ('products', '0004_product_wishlist_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='saved_items',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='products.product'),
        ),
        migrations.DeleteModel(
            name='BrandRepresentative',
        ),
    ]
